# Generated by Django 4.0.4 on 2022-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_IssueTrackingSystem', '0002_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('amélioration', 'amélioration'), ('tâche', 'tâche')], max_length=50),
        ),
    ]
