# Generated by Django 4.0.4 on 2022-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_IssueTrackingSystem', '0003_alter_issue_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('auteur', 'auteur'), ('collaborateur', 'collaborateur')], max_length=50),
        ),
    ]
