# Generated by Django 4.0.4 on 2022-12-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_IssueTrackingSystem', '0004_alter_contributor_permission_alter_contributor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
    ]
